# Project metadata
sonar.projectKey=StudCall_Antonin
sonar.projectName=StudCall
sonar.projectVersion=1.0

# Paths to sources
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/.next/**, src/**/*.test.tsx, src/**/*.test.ts, src/test/**

# Test paths
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx, src/**/*.test.ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# TypeScript configuration
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
