# Project metadata
sonar.projectKey=StudCall_Antonin
sonar.projectName=StudCall
sonar.projectVersion=1.0

# Paths to sources
sonar.sources=studcall/src
sonar.exclusions=**/node_modules/**, **/.next/**, studcall/src/**/*.test.tsx, studcall/src/**/*.test.ts, studcall/src/test/**

# Test paths
sonar.tests=studcall/src
sonar.test.inclusions=studcall/src/**/*.test.tsx, studcall/src/**/*.test.ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# TypeScript configuration
sonar.typescript.tsconfigPath=studcall/tsconfig.json
sonar.javascript.lcov.reportPaths=studcall/coverage/lcov.info
